### ISSUE TITLE
paper: lessons learned section

### ISSUE THREAD

**Issue by surli** [Spirals-Team/repairnator#145]
Problem: test Isolation issues (server running on a port, share tmp folder), solution: docker
Problem: Memory consumption, out of memory
Problem: Disk consumption, out of disk space error
Non standard build processes (build changing source files)
Travis outage
Coarse grained notion of build failure vs fine-grained notion of assertion error 
21/03: Change in API travis for log ids
02/04: out of disk because we don't clean the docker images, we loose three days of data 
multimodule

**Comment by fermadeiral** [comment]
Bears paper done.
