### ISSUE TITLE
bug: in case a final / remain in push URL, the push will fail

### ISSUE THREAD

**Issue by surli** [Spirals-Team/repairnator#168]

**Comment by fermadeiral** [comment]
Simon, I don't understand that issue. Could you elaborate on it for me, please?

**Comment by surli** [comment]
The remote repo should be exactly on the form:

`https://github.com/user/repo`

A remote repo like: `https://github.com/user/repo/` or `https://github.com/user/repo.git` can led to a bug when pushing.
