### ISSUE TITLE
Validation phase 2: manually analysis to confirm if there is actually a bug.

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/repairnator#266]

**Comment by surli** [comment]
Is this one finished?

**Comment by fermadeiral** [comment]
No. This one will be finished when we stop to collect bugs. It's the last validation before the benchmark be actually ready.

**Comment by fermadeiral** [comment]
I'm closing this one because it is like "run scanner for Bears", i.e. it's a part of the process on building the benchmark, and we already have the four main steps that compose the entire process on our dashboard (spreadsheet).
