### ISSUE TITLE
Enclose each step of Repairnator in a timeout

### ISSUE THREAD

**Issue by surli** [Spirals-Team/repairnator#351]

**Comment by surli** [comment]
We got a lot of stucked docker containers because of non responding mvn commands. I think we should actually put a timeout for each step of Repairnator process.

**Comment by fermadeiral** [comment]
It seems a good idea. How would we choose the timeout for each step? I mean, each step differs (maybe a lot) regarding the time of execution, e.g. clone can be way faster than test, thus we should probably put a timeout for test greater than for clone. Maybe we could define, for each step, a timeout based on previous experiments, e.g. for step clone the average (or median) execution time is x, then we get this x to be the timeout for step clone? WDYT?

**Comment by surli** [comment]
I was actually thinking about 3 different mechanism:
  1. for all steps using maven goal, to use the same mechanism as Travis: 10 minutes without log = timeout,
  2. for repair steps, to use continue using our current timeouts,
  3. for other steps, to define an absolute timeout (and yeah, we can use your idea there)

**Comment by fermadeiral** [comment]
This sounds a good plan.

**Comment by surli** [comment]
For the record, step one might be done for free using changes proposed in: https://github.com/apache/maven-invoker/pull/1

**Comment by surli** [comment]
Actually I think I won't do step 3: each time the build got stuck it was because of Maven goal, so I proposed to already close this issue. WDYT @fermadeiral ?

**Comment by fermadeiral** [comment]
> each time the build got stuck it was because of Maven goal

In this case, it's not necessary by *now* to put timeout in the other steps. I agree about closing this issue. If we have problems in the future because of the other steps, then we put timeout for them.
