### ISSUE TITLE
refactoring: Clean references to Luc in the code

### ISSUE THREAD

**Issue by surli** [Spirals-Team/repairnator#364]
It would be better to pass references to the committer user as a process argument.

**Comment by surli** [comment]
It should be done for the launch at ICSE

**Comment by fermadeiral** [comment]
How do you intend to do that? Just to know: every person that run repairnator (always) should get branches done by Luc as author? In other words, is this not a variable supposed to be changed by repairnator users?

**Comment by surli** [comment]
> is this not a variable supposed to be changed by repairnator users?

Yes it should be.
