### ISSUE TITLE
clean librepair-experiments: remove bad branches (incl. those with only one commit)

### ISSUE THREAD

**Issue by surli** [Spirals-Team/repairnator#372]
Why those have only one commit? https://github.com/Spirals-Team/librepair-experiments/branches/all?utf8=%E2%9C%93&query=dubbo

**Comment by surli** [comment]
Check if it exists branches since december with only one commit.

**Comment by surli** [comment]
They do: https://github.com/Spirals-Team/librepair-experiments/tree/JMRI-JMRI-331455326-20180121-151514_bugonly

My guess is that they might come from builds stuck when launching repair tools: they the second commit after repair tools cannot be pushed and the third one at the end of the process neither. 

However we still have the repairnator.json file.
WDYT we should do we those branches / build @monperrus ?

**Comment by monperrus** [comment]
We need to specify what's a wellformed repairnator.json, ie the minimum amount of information there.
It may be a JSON schema.

Then we can go over all branches and:
1) delete the ones without a wellformed repairnator.json
or 2) re-compute it

WDYT?

**Comment by surli** [comment]
So for me we have 4 different cases: 

1. A branch with a wellformed JSON and 3 or 4 commits -> everything's ok
2. A branch with a wellformed JSON and only 1 commits -> something went wrong during repairing phase
3. A branch with a wellformed JSON and more than 4 commits -> something went wrong during pushing phase
4. A branch with a malformed JSON

I propose the following: do a massive cleanup of cases 3 and 4, and keep build number to try to compute them again.
Cases 2 seems more tricky: we might have new cases with only 1 commit if the repair tools get stuck, so I would suggest to keep them as they are.

**Comment by monperrus** [comment]
> I propose the following: do a massive cleanup of cases 3 and 4, and keep build number to try to
> compute them again.
OK for me.

Note that by well-formedness, I don't only mean it's valid JSON, I also mean they contain the right
fields (hence this idea of JSON schema)

**Comment by surli** [comment]
> Note that by well-formedness, I don't only mean it's valid JSON, I also mean they contain the right fields (hence this idea of JSON schema)

It's what I had in mind. I propose that we define this schema together in a PR.

**Comment by monperrus** [comment]
trash branches https://github.com/surli/backup-experiments

**Comment by surli** [comment]
The cleaning process just finished. So the number of deleted branches is: 1 612.
