### ISSUE TITLE
Fix email notification: the branch name is wrong for PR fixes

### ISSUE THREAD

**Issue by surli** [Spirals-Team/repairnator#414]
Example on the recent mail coming from Astor patch:

> Hurray !

>Patch(es) has been found for the following build: http://travis-ci.org/alibaba/dubbo/builds/344699459.
Data about patches has been pushed on the following branch: https://github.com/Spirals-Team/librepair-experiments/tree/alibaba-dubbo-344699459-20180222-100508.

>Follow those instruction to create a pull request:
mkdir dubbo
cd dubbo
git init
git fetch https://github.com/alibaba/dubbo.git master
git checkout -b patch FETCH_HEAD
vi [file_to_patch]
git commit -m "tentative patch" -a
git push https://api.github.com/repos/lucesape/dubbo

The branch to fetch was however `2.5.X` and not master.

**Comment by surli** [comment]
Apparently it's particularly the case when the build is about a PR: 

> Patch(es) has been found for the following build: http://travis-ci.org/andreendo/Exemplo01/builds/358555930.
Data about patches has been pushed on the following branch: https://github.com/Spirals-Team/librepair-experiments/tree/andreendo-Exemplo01-358555930-20180326-210256.
Follow those instruction to create a pull request:
mkdir Exemplo01
cd Exemplo01
git init
git fetch https://github.com/andreendo/Exemplo01.git master
git checkout -b patch FETCH_HEAD

Actually here the checkout should be on the fork: https://github.com/GabrieldeCarli/Exemplo01

**Comment by monperrus** [comment]
I'm trying to check the patch for the recent CodeUTeam33/CodeU NpeFix patch

but I'm stuck.

Is this because of this bug?

**Comment by surli** [comment]
Indeed. Travis build says it comes from a PR so you should fetch the bug not from master branch but from the branch of the PR.

**Comment by monperrus** [comment]
Then, I'd say that fixing this is high priority.
