### ISSUE TITLE
question what's the value of timeoutTestExecution in Nopol configuration

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/repairnator#416]
See https://github.com/SpoonLabs/nopol/blob/6b45fc9e52490e19da108ca67455882030181996/nopol/src/main/resources/default-nopol-config.ini#L3

(If it's too low, this may partially explain why we get so few patches)

**Comment by surli** [comment]
It's currently set to 300 (seconds I imagine)

https://github.com/Spirals-Team/repairnator/blob/8bc8d903624f5aa39c33c81a5af0cbe6f5be87b2/repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/NopolRepair.java#L119

**Comment by monperrus** [comment]
yes seconds. This is OK.

about timeout, what's does this mean in NopolRepair?
```
                 int timeout = (TOTAL_MAX_TIME - passingTime) / 2;
                 if (timeout < MIN_TIMEOUT) {
                    timeout = MIN_TIMEOUT;
                 }
```

**Comment by surli** [comment]
> about timeout, what's does this mean in NopolRepair?

I use a budget when using Nopol: in total I allocate 4 hours of run and I divide it by two for each run of Nopol so 2 hours the first run, 1 hours the next if it indeed takes 2 hours for the first, etc. 
And I cannot allocate less than MIN_TIMEOUT which is 5 minutes or something like that.

**Comment by monperrus** [comment]
OK. FYI: Ye is fixing bugs in Nopol. Does Repairnator always take the latest version?
