### ISSUE TITLE
Question on notifiers.

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/repairnator#430]
For the PR #429, I'm currently working on notifiers. I realized that all launchers, except by the pipeline one, have the argument `notifyEndProcess`. However, I didn't find this working in the module `repairnator-realtime`, i.e. I didn't find the `notifyEnd` method from `EndProcessNotifier` being called.

Question on the module `repairnator-realtime`: what I just described is a bug or the notifier is not supposed to be in that module? My point is: either there is code missing (to make the notifier works) or there is more code than it should have (the argument `notifyEndProcess` and the other ones related to email notification shouldn't be pass to the launcher of that module).

**Comment by surli** [comment]
Contrary to other modules of Repairnator such as the scanner or the dockerpool, `repairnator-realtime` aims at being always running without interruption.
Then it makes no sense to use a notifier for the end of the process. That's why I did not put it in.

**Comment by fermadeiral** [comment]
Ok. Thus can I remove the arg `notifyEndProcess` from that module?

Another question: is the notifier engine being used somewhere in that module? The notifier engine has been initialized, but I still didn't find usage of this.

**Comment by surli** [comment]
> Thus can I remove the arg notifyEndProcess from that module?

Yup. I've been a bit fast when doing my cut/paste there.

>  is the notifier engine being used somewhere in that module? The notifier engine has been initialized, but I still didn't find usage of this.

Right now, it's not used indeed. You can remove it too.

**Comment by fermadeiral** [comment]
Deal.
