### ISSUE TITLE
to maximize local reproducibility, we should use the same docker image as travis

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/repairnator#438]
which is quay.io/travisci/travis-jvm

**Comment by surli** [comment]
Actually this docker image is 3 years old so I don't think Travis is still using it.
 
Moreover, the reproducibility problem is not really about using the same docker images as using the same script: meaning we should use their script builder to create the proper building script from .travis.yml before running any docker image: see, https://github.com/travis-ci/travis-build

**Comment by surli** [comment]
After having looked on travis-build and travis docker images, I suggest to keep our current way to reproduce errors. I close this ticket for now.
