### ISSUE TITLE
Arg skip-failing in Scanner.

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/repairnator#443]
The arg `skip-failing` apparently is used only in Bears mode. I saw we use this in `ProjectScanner`, but apparently this arg is never really passed by the scripts. In fact, it seems to me we can make the things work in `ProjectScanner` without this arg. Do you remember why we put it? Do you see an actual usage for this? Because maybe we don't need it anymore, thus we could remove it.

**Comment by surli** [comment]
I think we added it to only get the passing/passing builds from Bears when scanning. I really don't know if we might need it again: let me know...

**Comment by fermadeiral** [comment]
Humm...
I will wait the PR #429 to be closed, then I will look to the code in the scanner and I will see if we can just remove it (by now, it seems to me that we can). Then I will open a new PR only for the changes related to this. I will keep this issue opened by now.

**Comment by fermadeiral** [comment]
Closed by #456

**Comment by fermadeiral** [comment]
Closed by #456
