### ISSUE TITLE
Fix RateLimit issue with Github in TravisCI

### ISSUE THREAD

**Issue by surli** [Spirals-Team/repairnator#459]

**Comment by fermadeiral** [comment]
This issue is really bothering me because almost everytime I do a PR I got failing builds with failing tests. I searched a little bit and it seems this problem happens when the PR is coming from forks, because the environment variables are not used (in this case, the ones related to GitHub authentication turn the GitHub limit so low). Do you have any idea to fix that?

**Comment by surli** [comment]
> PR is coming from forks, because the environment variables are not used

Yes it's actually related to this: https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions

And we cannot do anything against it directly.

I propose to take those actions:
  1. Prepare another CI like Jenkins - with proper authentication - to run on PRs, then we'll have two distincts diagnostics
  2. We should **REALLY** refactor the test of repairnator-pipeline, we only use integration test and they're ugly

**Comment by fermadeiral** [comment]
Ok. This looks like a kind of big and not that fast to do, mainly the second action, thus it may be better to open one issue to each action? Because, in fact, we will not fix the GitHub rate limit (which this issue is about), right?

**Comment by fermadeiral** [comment]
Just for the record, I will try to focus first in the first action.

**Comment by surli** [comment]
> Just for the record, I will try to focus first in the first action.

Actually we already have a Jenkins CI at INRIA, and I already began to work on it, so maybe let me handle this one.

> thus it may be better to open one issue to each action

Yep

> Because, in fact, we will not fix the GitHub rate limit (which this issue is about), right?

Exactly, I was waiting your reaction to close this one and create the other tickets.

**Comment by fermadeiral** [comment]
> Actually we already have a Jenkins CI at INRIA, and I already began to work on it, so maybe let me handle this one.
Ok, then.

> Exactly, I was waiting your reaction to close this one and create the other tickets.
Thank you.
