### ISSUE TITLE
Arg workspace in Pipeline.

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/repairnator#460]
I don't understand the usage of the arg `workspace` in the pipeline module. I found it is used only on tests. Is this arg really necessary? If yes, could you explain me why?

**Comment by surli** [comment]
It's just a small parameter that's used almost everywhere in the pipeline :p

the arg `workspace` set RepairnatorConfig.workspacePath which is then given to inspector, which use it to build pathes like repoLocalPath or m2LocalPath.

**Comment by fermadeiral** [comment]
Humm...Ok. I just thought strange because I didn't find it in any script too. Apparently we use it always in its default value.

Could you just change it then for me: `opt2.setHelp("Specify path to output serialized files");` ?

**Comment by surli** [comment]
> Humm...Ok. I just thought strange because I didn't find it in any script too. Apparently we use it always in its default value.

Actually now we're using a docker image to run the pipeline we always use the default value. But if you want to use repairnator-pipeline in command line, in can be a really useful parameter.

> Could you just change it then for me: opt2.setHelp("Specify path to output serialized files"); ?

You want to refine the help message ?

**Comment by fermadeiral** [comment]
> You want to refine the help message ?

Yes, because it's the same message than the arg `output`, thus it may be confusing.

**Comment by surli** [comment]
Fixed by #466
