### ISSUE TITLE
Email notifier engine.

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/repairnator#462]
The notification by email doesn't work (at least for me) by passing only the smtp and my email address (PS: I'm not behind any proxy). This is working for me now because I did local changes in the class `EmailNotifierEngine`, where the email `librepair@inria.fr` is hard coded as being the sender of the email. To make this work for me, I had to put my own email address as the sender and also to authenticate myself in the `Session` (and some little things more).

My question is: is the way that it is now supposed to work for everybody? If yes, what did I miss? If no, do you have something in mind for the next steps on email notification? If yes, I would be glad if you share it with me and assign this issue to me.

**Comment by surli** [comment]
> My question is: is the way that it is now supposed to work for everybody? 

Yes, as soon as you use a SMTP you can manage, or if you use the SMTP of INRIA: your current smtp certainly blocks email coming from the domain "inria.fr", as it should be actually :) 

We should make the sender email adress an element of the Repairnator configuration to avoid issues like you have.

**Comment by surli** [comment]
Indeed :)
