### ISSUE TITLE
Refactoring: review dockerpool module fields and paramenter passing (and other modules too, because RepairnatorConfig really simplify a lot of things now).

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/repairnator#471]
Now that all args are being stored in `RepairnatorConfig`, we might be able to clean some stuff like fields and parameter passing, e.g. the field `skipDelete` seems to be not necessary anymore in `RunnablePipelineContainer` and `AbstractPoolManager`.

**Comment by surli** [comment]
Yes!
