### ISSUE TITLE
chore: ajouter la sauvegarde de la BD sur repairnator

### ISSUE THREAD

**Issue by surli** [Spirals-Team/repairnator#478]

**Comment by surli** [comment]
Done. Some docs are pushed on doc directory.

**Comment by monperrus** [comment]
in French, original!

**Comment by monperrus** [comment]
For the record, we have backups here: https://github.com/Spirals-Team/repairnator/tree/master/resources/data/mongodb-dump

**Comment by btellstrom** [comment]
https://owncloud.tutafey.eu/index.php/s/jbOnAIehvsqalEG Is the one last made by Simon before we moved the Repairnator instance.

**Comment by monperrus** [comment]
We push the backups on https://github.com/repairnator/mongodb-backups in a compressed way (good compression, xz, 7z).
