### ISSUE TITLE
logs directory empty after following instruction in quickstart

### ISSUE THREAD

**Issue by surli** [Spirals-Team/repairnator#479]

**Comment by surli** [comment]
@monperrus I did not manage to reproduce your problem, even when trying on two different machines. 
Could you try back with the following instruction, please?

Instruction: 
1. Clone the repo
2. Create a directory `/tmp/testdir`
3. Change the repairnator/scripts/set_env_variable.sh to put `HOME_REPAIR=/tmp/testdir` and dumb values in `GITHUB_LOGIN` & `GITHUB_OAUTH`
4. Launch back `./scripts/repair_buggy_build.sh 352395977`
5. Wait for the docker container to finish and look in `/tmp/testdir/logs/XXX` directory where XXX is a timestamp
6. If you do not have any file in this directory, do a `docker logs <container> |less` on your previous container and cut & paste here all lines before the first mention of `CloneRepository` (the first 10 lines or so)

thanks!

**Comment by monperrus** [comment]
What if you put a bad |GITHUB_OAUTH?|

**Comment by surli** [comment]
> What if you put a bad |GITHUB_OAUTH?|

for this test it's not a problem you an use "toto" or whatever

**Comment by surli** [comment]
ping @monperrus could you try it again? 
Now you just need to do the following: 
1. Clone repairnator
2. Launch the script ./repairnator/scripts/repair_buggy_build.sh 352395977

No need to configure anything anymore. And tell me if you get something in $HOME/repairnator/logs

**Comment by monperrus** [comment]
It works now, thanks!
