### ISSUE TITLE
Astor: there are actually multiple modes, add support for JMutRepair

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/repairnator#523]
Astor is a repair framework with multiple techniques.

It means that:

* [ ] `AstorRepair` should be called `Astor<Mode>Repair`, eg `AstorJGenProgRepair` (we also need to change the prefix in the email)
* [ ] add `AstorJMutRepairRepair` for jMutrepair.
* [ ] add `AstorJKaliRepair` for jKali.

**Comment by surli** [comment]
In order to achieve this task properly, is there identified test cases in Nopol for each repair techniques? Or is it each time the same case used? 
Could you point me out the test case(s) I can use @martinezmatias?

**Comment by monperrus** [comment]
Do you mean in Astor?

**Comment by surli** [comment]
Yes I mean to point out the current test cases in Astor for me to take them back and put them in repairnator.

**Comment by martinezmatias** [comment]
Hi @surli 
You can find a test case here:
https://github.com/SpoonLabs/astor/blob/master/src/test/java/fr/inria/astor/test/repair/approaches/MutRepairTest.java#L27

**Comment by surli** [comment]
So I assume it's for JMutRepair, and another one for JKali?

**Comment by martinezmatias** [comment]
For jKali those tests:
https://github.com/SpoonLabs/astor/blob/master/src/test/java/fr/inria/astor/test/repair/approaches/jKaliTest.java#L32

**Comment by surli** [comment]
Great. Thanks @martinezmatias :)
