### ISSUE TITLE
take new version of NpeFix

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/repairnator#524]
@tdurieux has fixed some bugs, we should take the new version of NpeFix in repairnator.

**Comment by surli** [comment]
@tdurieux any plan to release maven-repair?

**Comment by tdurieux** [comment]
You did the previous release because I don't have the access for sonatype

**Comment by surli** [comment]
Ahah. OK. So you don't mind if I release it?

**Comment by tdurieux** [comment]
Not really, but I have an issue with the last version of nopol.
It does not work with the plugin.

**Comment by surli** [comment]
For me it's not a problem because I don't use nopol with maven-repair. It would be only for NPEFix.

**Comment by surli** [comment]
Fixed by #526

**Comment by monperrus** [comment]
done
