### ISSUE TITLE
Add a new argument JAVA_OPTS for all scripts

### ISSUE THREAD

**Issue by surli** [Spirals-Team/repairnator#566]
We should be able to use custom java options (like `Xmx`) for JVM when running our tools. It should be an option in `repairnator.cfg` used in every scripts.

**Comment by surli** [comment]
Fixed in #623

**Comment by btellstrom** [comment]
@fermadeiral I seem unable to add labels to anything, I believe I do not have the "rank" in the project to do that

**Comment by surli** [comment]
@btellstrom even without adding label, you can add "WIP" and "review" when the work is in progress / ready to review. It helps us ;)
