### ISSUE TITLE
simplify dashboard for ICSE live demo

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/repairnator#573]
* title: "What is Repairnator doing right now?"
* subtitle: "Repairnator is an automated program repair bot for Travis CI"
* no other link
* Github icon to click (as in Travis pages)
* at the bottom: "Feedback? Comments? Ideas? Drop us an email (mailto:simon,martin)"
* remove menu/tabs at the top
* remove all pie charts but "build status all times"
* keep only one time-line with only one line "number of reproduced builds"
* keep table: if the date is today, write "Today" instead of the date. if the time is recent write "X minutes ago" or "X hours ago", it will help much for the live demo

**Comment by surli** [comment]
Fixed.
