### ISSUE TITLE
Review checkbranches module.

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/repairnator#586]
I propose that checkbranches module be responsible for:

- Reproducing the branch;
- Verifying if it contains mandatory files (like repairnator.json file);
- Matching json files against schemas;

WDYT? Do I miss something?

**Comment by surli** [comment]
it looks ok for me

**Comment by fermadeiral** [comment]
@surli, I'm starting with a cleaning in checkbranches module since nobody has touched on it for a while.

First, I'm thinking to extract a class called `DockerHelper` (to put it in the core module), containing methods from `dockerpool/AbstractPoolManager`. Reason: there are some duplicate methods between `checkbranches/Launcher` and `dockerpool/AbstractPoolManager`, e.g. `findDockerImage`. So the new helper class would be used for both modules.

Second, after performing what I just described, maybe the class `dockerpool/AbstractPoolManager` can be merged into `dockerpool/Launcher`, because I believe that it might be really small, and it might make easier to understand the dockerpool module without it. OR maybe to create an `AbstractPoolManager` also in `checkbranches` module, so the two modules that use docker would match, also making easier to understand the things in the project.

Third, in `checkbranches/Launcher` there is that statement: `this.config.setSerializeJson(true);`, but if I properly understood the code of such module so far, no json file is created as output. Would you like to have `TreatedBranchTracking`, which would be similar to `dockerpool/TreatedBuildTracking`, maybe also containing the diagnostic of the check branch?

WDYT?

**Comment by surli** [comment]
> For Repairnator, the human patch should be checked (when it exists)

Yes it should.

**Comment by fermadeiral** [comment]
@surli, I'm thinking in putting a check for the number of commits too. For Bears, it needs to be 3 commits for failing/passing and 4 commits for passing/passing. Are you interested on this check too? If yes, how many commits is for Repairnator?

**Comment by surli** [comment]
> Are you interested on this check too? If yes, how many commits is for Repairnator? 

Hmm not really for now.

**Comment by fermadeiral** [comment]
Several PRs were done and the review of the checkbranches module was completed.
