### ISSUE TITLE
pom.xml being take from sub-module project.

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/repairnator#591]
When running repairnator with repairnator, the pom.xml file is being get from the sub-module project bears-usage.

**Comment by surli** [comment]
Actually it's a desired behaviour: we don't have a pom.xml file in the root directory, then Repairnator is looking for the pom.xml file in sub-directories using alphabetical order. Then bears-usage is the first one it finds.

**Comment by fermadeiral** [comment]
> we don't have a pom.xml file in the root directory, then Repairnator is looking for the pom.xml file in sub-directories using alphabetical order

I get this idea. However, the way the process is right now, we will **never** reproduce bugs and their patches from projects like repairnator (which is a project in our list of projects BTW).

> Actually it's a desired behaviour

Good, it's one less things to fix.

**Comment by surli** [comment]
> However, the way the process is right now, we will never reproduce bugs and their patches from projects like repairnator (which is a project in our list of projects BTW).

Indeed. And I'm open to get ideas to improve that.

**Comment by fermadeiral** [comment]
> I'm open to get ideas to improve that.

Ok. I will think about it and if I get something that looks like good I will let you know.
