### ISSUE TITLE
MavenModelResolver is erroring on some pom.xml

### ISSUE THREAD

**Issue by surli** [Spirals-Team/repairnator#597]
A first unit test were implemented but discarded in #594. It's a good start.

**Comment by fermadeiral** [comment]
@surli, I saw you did a commit related to that issue. Could you please tell me what is the status of this? In other words, was the issue fixed, partially fixed, or not at all?

**Comment by surli** [comment]
Fixed.

**Comment by fermadeiral** [comment]
Oh nice.
