### ISSUE TITLE
Move to somewhere else methods from GitHelper that are not related to git

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/repairnator#599]
Some methods extracted from steps have been put in `GitHelper` such as `copyDirectory` and `removeNotificationFromTravisYML` (and some others) that are not really related to git. I propose we move them for somewhere else, maybe a new helper or utility class for the steps. WDYT? I'm opened for suggestions.

**Comment by surli** [comment]
It might be an interesting thing to do but it surely related to #361 
I asked Benjamin to take #361 so I propose that he does this one too: it's a good first issue IMHO

**Comment by fermadeiral** [comment]
> it surely related to #361

Related from far, since the methods I just told there is nothing to do with git, and consequently nothing to do with removing jgit from repairnator.

> I asked Benjamin to take #361 so I propose that he does this one too: it's a good first issue IMHO

It's indeed a good first issue. Proposal accepted. Could you please actually assign him for the issues you are asking him to take so I can see it on github (and then not lose my time working by chance in the same thing as him)?
I also propose that he takes this one first than the other one, because this one is way faster to do, and he could be able to start to interact with the code of repairnator and with us in a PR. WDYT?

**Comment by surli** [comment]
> I also propose that he takes this one first than the other one, because this one is way faster to do, and he could be able to start to interact with the code of repairnator and with us in a PR. WDYT?

We have a meeting next week, we'll discuss about that ;)

**Comment by btellstrom** [comment]
Hi
I appreciate the label, and FYI this is my github login so you can @ me in the future
/Benjamin

**Comment by fermadeiral** [comment]
@btellstrom you shouldn't have tell us this. Now we are going to bother you a lot ^^

**Comment by fermadeiral** [comment]
Hi @monperrus 

> beyond `copyDirectory` and `removeNotificationFromTravisYML`, what's the exhaustive list of methods to be moved?

Here is the list of methods:
- `copyDirectory`
- `deleteFile`
- `removeNotificationFromTravisYML`
- `removeGhOauthFromCreatedFilesToPush`

> in what package should the new helper class go?

Since all these methods are related with operations on files, my suggestion would be that the new class is named `FileHelper` (or some variant of this).
About the package where it should be moved in, I see two options:
- To create a package `fr.inria.spirals.repairnator.process.files` (module `repairnator-pipeline`)
- To move the new class to the existing package `fr.inria.spirals.repairnator` (module `repairnator-core`)

IMHO, I think the first option is better.

> Thanks --Martin

No problem.

**Comment by fermadeiral** [comment]
This one was done in #645, right?

**Comment by surli** [comment]
Indeed

**Comment by surli** [comment]
Fixed by #645
