### ISSUE TITLE
Finding pom.xml: skip submodules

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/repairnator#602]
@surli in #591 you said:

> Actually it's a desired behaviour: we don't have a pom.xml file in the root directory, then Repairnator is looking for the pom.xml file in sub-directories using alphabetical order. Then bears-usage is the first one it finds.

I get that the pom.xml file is not in the root so Repairnator starts to search it in folders. My question now is: is a desired behavior that the pom.xml is obtained from a sub-module project? Because if it's not, then I can have a direction on how to fix the issue I exposed in #591.

**Comment by surli** [comment]
It might be a good heuristic to skip pom.xml files coming from a submodule.
