### ISSUE TITLE
Project metrics seem buggy.

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/repairnator#610]
We have three project metrics:
- numberSourceFiles (calculate in `ComputeSourceDir`)
- numberTestFiles (calculate in `ComputeTestDir`)
- numberLibraries (calculate in `ComputeClasspath`)

The correctness of these metrics is not being checked, and they seem buggy based on values generated by repairnator in `bears.json` file.

**Comment by fermadeiral** [comment]
Contract for `numberLibraries` (agreement in #624): for Repairnator, it's on the failing module (it's already correct); for Bears, it's on all modules.

**Comment by surli** [comment]
Put it as documentation in the code, please.

**Comment by fermadeiral** [comment]
The `numberLibraries` calculation for Bears will remain the same as for Repairnator: it's on the failing module.

**Comment by surli** [comment]
fixed in #656
