### ISSUE TITLE
Make sure that serialized json files still can be used as input for MongoDB

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/repairnator#613]
@surli, there is a thing happening in all serialized json files. Here I will use `hardwareInfo.json` as an example. In the first time that data is serialized in such file, it's ok. But, since the second time, it invalidates the json file. See an example:

```
{
	"runId": "test",
	"buildId": "369997088",
	"hostname": "fermadeiral-laptop",
	"nbProcessors": 4,
	"freeMemory": 69449672,
	"totalMemory": 78643200
} {
	"runId": "test",
	"buildId": "191511078",
	"hostname": "fermadeiral-laptop",
	"nbProcessors": 4,
	"freeMemory": 53280920,
	"totalMemory": 62390272
}
```
My question is:  does it can make our lifes more difficult in the future, or is this just fine?

**Comment by fermadeiral** [comment]
I'm not that sure it will work, but I also still didn't try it. I was thinking to try a change in `JSONFileSerializerEngine`, to make its implementation really on a json file, because I believe that to make the json file a valid one we would need to something that results this:

```
[{
	"runId": "test",
	"buildId": "369997088",
	"hostname": "fermadeiral-laptop",
	"nbProcessors": 4,
	"freeMemory": 69449672,
	"totalMemory": 78643200
}, {
	"runId": "test",
	"buildId": "191511078",
	"hostname": "fermadeiral-laptop",
	"nbProcessors": 4,
	"freeMemory": 53280920,
	"totalMemory": 62390272
}]
```

**Comment by surli** [comment]
Actually if I'm right the produced concatenate JSON file can be used as input for MongoDB and it was my main concern.

I don't really know what's the need to get a proper JSON file here.

**Comment by fermadeiral** [comment]
> Actually if I'm right the produced concatenate JSON file can be used as input for MongoDB and it was my main concern.

Ok, I will check that on MongoDB side for me to be sure.

> I don't really know what's the need to get a proper JSON file here.

I didn't say there is a need. I actually asked you if this was a problem when I opened the issue.

**Comment by surli** [comment]
I found back a script that does exactly what we discuss: it put the results from a JSON file in a mongoDB collection.
So for me this is checked. I'm closing this one.
