### ISSUE TITLE
Question on number of libraries metric on repairnator side.

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/repairnator#624]
Currently, the number of libraries metric is set with the number of libraries from the failing module. For Bears, I'm going to do it considering all modules, since this info is in the property group `projectMetrics` in `bears.json`. For Repairnator, I would like to know if the way it is now is ok or if it was supposed to be on all modules too.

**Comment by surli** [comment]
I'm not the sure the number of libraries for all the modules is really relevant for repairnator. So let's keep only the libraries of the failing module.
