### ISSUE TITLE
Add projectRootPomPath property for both Bears and Repairnator.

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/repairnator#627]
I'm still not sure if I'm going to do it for Bears, but I already would like to ask this: I'm considering to add a property in the `bears.json` file, more specifically in the group `reproductionBuggyBuild`. It's the path of the `pom.xml` used in the reproduction (which is the one obtained by calling `AbstractStep.getPom()`). I realized that maybe this can be useful when fixing #602, because I realized we can obtain a pom that we didn't expected (or which is not the pom of the "main" project inside a messy/complex repo). So, I think this info can be useful in the `bears.json` file, since we don't need to look at logs to see which pom was taken to reproduce a given bug, i.e. we can know directly from the bugs in the benchmark this info. Would this info be useful for Repairnator?

**Comment by surli** [comment]
I think it's already in repairnator.json on the form of the failing module path, but I might be wrong. So yeah it can be useful.

**Comment by fermadeiral** [comment]
Ok so please let's align our thoughts before I do something that will be useless/wrong in the end: using a multi-module project as example, which contains a pom in the root, and a pom in each module, we currently have this in the `failingModule` property in `bears.json` (it's the same value for `repairnator.json` too):
`"failingModule": "/home/fernanda/git/repairnator/workspace/fermadeiral/test-repairnator-bears/386337343/test-repairnator-bears-patchstats"`
For this project in specific, I have pictured we would have the following in the `pomPath` property:
`"pomPath": "/home/fernanda/git/repairnator/workspace/fermadeiral/test-repairnator-bears/386337343/pom.xml"`
i.e. the pom in the root, not the one in the failing module. I'm not completely sure right now, but I believe this is the pom that `AbstractStep.getPom()` would return.
Do you agree with that, or my thought for the a value of the property results in an useless info?

**Comment by surli** [comment]
OK that's not what I had in mind, but still it might be useful. So ok, but call it "projectRootPomPath" then.

**Comment by surli** [comment]
fixed in #656
