### ISSUE TITLE
Question on MetricsSerializer and MetricsSerializer4Bears

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/repairnator#628]
For both serializers, two files have been created: json and csv. However, the csv is empty, because in the implementation of these two serializers the work is only done for json. My question is: is it useless to record those info in a csv file or is the implementation for this missing? If the former is correct, maybe we should not record the (empty) file.

**Comment by surli** [comment]
Maybe we should, but it's not that important, is it?

**Comment by fermadeiral** [comment]
> but it's not that important, is it?

You are asking me 1) if the metrics cvs file is not important or 2) if not recording the empty file is not important?

**Comment by surli** [comment]
I don't think the implementation is missing: we don't care anymore about CSV file. So the empty CSV files are useless, but it's not really an issue IMHO.

**Comment by fermadeiral** [comment]
> I don't think the implementation is missing: we don't care anymore about CSV file.

Good, this is what I wanted to know. I also don't care with them. For me, the json files are already doing the work.

> So the empty CSV files are useless, but it's not really an issue IMHO.

I also think it's not really an issue, I just wanted to know what is going on here (if they were important, I would have found a bug), and I also don't want to push a bunch of useless files in bears-achieve.
