### ISSUE TITLE
add ingredientstrategy parameter to Astor-JGenProg

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/repairnator#636]
This strategy should give better results:

    -ingredientstrategy fr.inria.astor.test.repair.evaluation.extensionpoints.ingredients.MaxLcsSimSearchStrategy

Version to take is 4b9e6945827972434782e3201f03aa74c3db26f8

Thanks to @chenzimin

**Comment by surli** [comment]
@btellstrom would you take this one?
The task would be to change a parameter in the class `AstorRepair` in repairnator-pipeline.

**Comment by btellstrom** [comment]
Can do. Just how urgent is it?

**Comment by surli** [comment]
Not that much. And at worst I'll take it if you haven't already done it.

**Comment by btellstrom** [comment]
What would I need to do to change the version? Have I misunderstood if I think it's just to do astorArgs.add("... with the two separate strings Martin wrote?

**Comment by monperrus** [comment]
+ modifying the test case to make sure it works as expected

**Comment by surli** [comment]
> What would I need to do to change the version?

You need to fix the version in the pom.xml file.

> Have I misunderstood if I think it's just to do astorArgs.add("...

Yep it should be something like that.

**Comment by surli** [comment]
> modifying the test case to make sure it works as expected

@monperrus @martinezmatias any idea how to check this specific behaviour in a test?

**Comment by monperrus** [comment]
it's an interesting testability question.

one solution would be to test the number of "repair attempts" (repair attempt = compilation + test
execution of the failing test case).

Is this information available in the Astor API?

**Comment by btellstrom** [comment]
You are more than welcome me if I am wrong, but I have a couple of questions.

Firstly, should a test to see if Astor works as expected be part of repairnator? Should it not be part of Astor itself to ensure that it works correctly, or is the simple truth that this can not be relied on so we must write a test case ourselves, and if it works well maybe even suggest it as a test to Astor?

Secondly, as I have understood the Astor docs, the default strategy is a random choice strategy, thus any test case checking the number of "repair attempts" could be misleading due to the random choice. As I wrote this I realised that a "solution" would be to check that the number of "repair attempts" are the same many times, but that could potentially also fail, although with a lower likelihood.

**Comment by surli** [comment]
> Firstly, should a test to see if Astor works as expected be part of repairnator? Should it not be part of Astor itself to ensure that it works correctly, or is the simple truth that this can not be relied on so we must write a test case ourselves, and if it works well maybe even suggest it as a test to Astor?

Actually Repairnator is really about integrated multiple tools, so here we test that this integration works as expected. So for me it's not testing the behaviour of Astor itself but the entire toolchain.

> one solution would be to test the number of "repair attempts" (repair attempt = compilation + test execution of the failing test case).

It looks a bit overkill for me: as I said above, for me it's only the integration that has to be tested here. I think that Astor contains an object to store its configuration: I suggest that for now we only check that this configuration is correctly set up.

We could improve this test in the future if we know a specific faulty program which can be repaired only when using this specific strategy.

**Comment by btellstrom** [comment]
As I have understood it, what we would need to do is to check that the Astor object that is "IngredientSearchStrategy" is an instance of MaxLcsSimSearchStrategy to see that this specific point of the configuration is correct. However, I seem unable to find where in Astor this object is created. According to [the docs](https://github.com/SpoonLabs/astor/blob/master/docs/extension_points.md) this should be an extensionPoint, which I assumed was loaded in AstorCoreEngine, but AstorCoreEngine does not seem to load any ingredient based extensionpoints [(line 1636)](https://github.com/SpoonLabs/astor/blob/master/src/main/java/fr/inria/astor/core/solutionsearch/AstorCoreEngine.java). Sadly, I am afraid I do not know how to proceed now. Is there a specific part of Astor that handles the ingredient extensionpoints that I have missed? 

@surli @monperrus do you have any suggestions?

**Comment by monperrus** [comment]
> As I have understood it, what we would need to do is to check that the Astor object that is
> "IngredientSearchStrategy" is an instance of MaxLcsSimSearchStrategy to see that this specific
> point of the configuration is correct. 
That's a good option. Maybe you need to do another PR in Astor first to expose more configuration.

**Comment by monperrus** [comment]
closed by #639
