### ISSUE TITLE
Logs from RunnablePipelineContainer are really difficult to analyze.

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/repairnator#637]
@surli, I'm thinking at changing the log messages from `RunnablePipelineContainer`. As several of threads are run at the same time, it's really difficult to search the messages for a specific build id. Worse, it's difficult to know which contained has finished (`21:02:49.282 [pool-2-thread-3] INFO  f.i.s.r.d.RunnablePipelineContainer - The container has finished with status code: 0`).

WDYT about putting at the beginning of all log messages in `RunnablePipelineContainer` the build id? For instance:

```
Start to build and run container for build id 361937455
(BUILD 361937455) Create the container: repairnator-pipeline_2018-06-20_1901_361937455_8cd9d433-243f-4ac4-bc0e-80fe59104298
(BUILD 361937455) Start the container: repairnator-pipeline_2018-06-20_1901_361937455_8cd9d433-243f-4ac4-bc0e-80fe59104298
(BUILD 361937455) The container has finished with status code: 0
(BUILD 361937455) Container will be removed.
```

For some log messages, the container name is presented, which contains the build id, but the name is long. I'm trying to find a way that makes possible to search very quickly some stuff.
I'm also opened for suggestions if you have some better idea.

**Comment by surli** [comment]
fixed in #656
