### ISSUE TITLE
bears: dockerpool is crashing

### ISSUE THREAD

**Issue by surli** [Spirals-Team/repairnator#644]
Dockerpool is crashing when running in bears mode against this list of builds: https://github.com/surli/bears-archives/blob/master/1-scanner/out/2018-05-27_133628_1421b428-e6ca-40cf-81b6-05142c67ac08_04-18-week1-bears-both/list_build_2018-05-27_1336_1421b428-e6ca-40cf-81b6-05142c67ac08_04-18-week1-bears-both_FAILING_AND_PASSING.txt

**Comment by surli** [comment]
@fermadeiral could you specify which branch of your fork do you use?

**Comment by fermadeiral** [comment]
Yes, it's this one: https://github.com/fermadeiral/repairnator/tree/prepare-run-bears
Every time I push in such branch, a docker image is built with my changes here: https://hub.docker.com/r/fermadeiral/repairnator/builds/

**Comment by surli** [comment]
Reproduction running on bears machine. Directory for logs: /home/repairnator/run-bears-fork/repairnator/logs/2018-06-29_174754_d8416710-b30c-482e-9145-21e35a96a993

**Comment by fermadeiral** [comment]
Oh, sorry. I sent it in your email because I forgot we will discuss that here.

**Comment by fermadeiral** [comment]
Crashed for the third time. This time, 27 out of 222 pairs of builds were processed.

The docker pool log doesn't show any error, and there is a lack of the final message. Moreover, only 23 pairs of builds are marked as TREATED, thus probably the end of the last 4 pairs is not detected. Some pair of these 4 (or more than one) are probably what has crashed the docker pool.

**Comment by surli** [comment]
So I ran it yesterday and it processes well the 222 pair of builds.
I think the crash were in fact coming from the way you were launching the process: if you were launching it by calling `./launch_dockerpool.sh <arguments>` the process was deleted when the SSH connection was closed, because it was attached to the console, so to the ssh connection.

In order to avoid that, you always need to launch this kind of process with a `nohup` like `nohup ./launch_dockerpool.sh <arguments>`.
Another way to do it is to call `disown` after the process is already launched:

```
shell$ ./launcher.sh &
[1] 12435
shell$ jobs
[1] running ./launcher.sh
shell$ disown %1
```
it will detach the job from the current console.
If you were already calling the launcher with a `nohup`: first, sorry for the lesson ;). And second, I also change the configuration to only launch 3 parallel docker containers instead of 4. It might be related to that.

So tell me!

**Comment by fermadeiral** [comment]
First: yes, I did `./launch_dockerpool.sh <arguments>`

> In order to avoid that, you always need to launch this kind of process with a nohup like nohup ./launch_dockerpool.sh <arguments>.

I tried this way once, but it's kind of strange, because what the command line shows to me was different from when I use that to launch the scanner in the repairnator machine. This is why I stopped to use nohup in bears machine. I thought that something was wrong.

> the process was deleted when the SSH connection was closed, because it was attached to the console, so to the ssh connection.

This is strange to me, because the crash happened 3 times with that list, but when I executed a list of 500 pairs, which took a lot of time, everything happened well. But I'm happy that this was the problem, at least it's easy to fix.

> If you were already calling the launcher with a nohup: first, sorry for the lesson ;). And second, I also change the configuration to only launch 3 parallel docker containers instead of 4. It might be related to that.

Thank you very much, I will do in the way you said from now.
