### ISSUE TITLE
push last version of mongodb dump at the end of august

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/repairnator#648]

**Comment by surli** [comment]
I just created and tested the dump, however it's 105 Mb which is larger than the authorized Github size for committing it (the limit is 100 Mb).
So I'm being uploading the file and I'll post the share link here soon.

**Comment by btellstrom** [comment]
For me there seems to be some issues with the dump. I assume it's a JSON-file? The encoding seem to be strange and when I try to import it into our database I receive and error 
```
ubuntu@repairnatormongodb:~/pastDatabase$ mongoimport -u "username" -p "password" --host localhost:27017  -d "repairnatorData" --file repairnator_0109_last 
2018-09-30T09:25:23.736+0000    no collection specified
2018-09-30T09:25:23.738+0000    using filename 'repairnator_0109_last' as collection
2018-09-30T09:25:23.826+0000    connected to: localhost:27017
2018-09-30T09:25:23.887+0000    Failed: error processing document #1: invalid character 'm' looking for beginning of value
2018-09-30T09:25:23.887+0000    imported 0 documents
```

**Comment by surli** [comment]
It's actually a mongodump, so you should use a `mongorestore` command, see the doc here: https://github.com/Spirals-Team/repairnator/blob/master/doc/chore/managedb.md

**Comment by btellstrom** [comment]
Fixed on new database. However, you mentioned previously it was quite a large size (20 GB) while this dumo only seem to contain 0.309 GB according to the database. I assume this is a subset of the entire database? Would we want the entire thing?

**Comment by surli** [comment]
> However, you mentioned previously it was quite a large size (20 GB) while this dump only seem to contain 0.309 GB according to the database.

I might have mentionned the uncompressed size, where the DB naturally compress things. You can check the date of first documents in projectInspector to be sure.

**Comment by btellstrom** [comment]
You seem to be correct, at least I was able to find documents from the beginning of 2017.

Closed.
