### ISSUE TITLE
test: test ComputeSourceDir / ComputeTestDir with jruby/jruby

### ISSUE THREAD

**Issue by surli** [Spirals-Team/repairnator#652]
The bug #650 was obtained when trying to fix a build from https://github.com/jruby/jruby. It looks like a project using heavily multi-modules.

We should test ComputeSourceDir and ComputeTestDir with their pom.xml file.

**Comment by btellstrom** [comment]
Am I correct in thinking that you want to create a ```testComputeSourceDirWithMultiModuleProject6``` with a build of their project? However, I am uncertain as to why you are specifying their pom.xml-file, since the only test I see where a pom.xml is specified is in TestMavenHelper, could you clarify why the pom.xml is important?

**Comment by surli** [comment]
> could you clarify why the pom.xml is important?

The steps `ComputeSourceDir` and `ComputeTestDir` are using the pom files to get the proper source and test directories by getting the right properties.
However in order to do that we have to parse the pom files which might involve to resolve their parents etc.

Moreover in some cases we are looking for a source directory of a submodule of a project: I think it was the case in #650. The idea here would be to import some pom files of this project (like the root one and maybe one of the submodule) and to check that the method we use in ComputeSourceDir / ComputeTestDir are working well. 

Is it more clear?

**Comment by btellstrom** [comment]
Okay, yes that is more clear. Thank you. 

However, I have assumed you want me to write a test similar to the previous ones, and I am uncertain where you specify the pom-files, all I seem to see that are explicitly specified are buildIDs. Is my previous assumption wrong or am I looking in the wrong place?

**Comment by btellstrom** [comment]
Okay, then I misunderstood slightly from the beginning. That makes things a lot clearer, thank you.

**Comment by btellstrom** [comment]
Should I have to create new mock classes for the different build (maybe only BuildToBeInspectedMocker?) objects then, since an inspector is needed for ComputeSourceDir? Or do you have a buildID in mind?

**Comment by surli** [comment]
> Should I have to create new mock classes for the different build

I don't understand your question. Here I was talking about creating only one test, not about refactoring the older ones.

**Comment by fermadeiral** [comment]
@btellstrom I can guide you in a PR for this if you want, before Simon reviewing it, like pair programming.

**Comment by btellstrom** [comment]
@fermadeiral that would be great! 

@surli as I've understood it I should use a `ProjectInspectorMocker` (since it is required by `ComputeSourceDir`), but that requires a `BuildToBeInspected` object, which we do not have a mocker for. Am I completely lost or at least on the right track?

**Comment by fermadeiral** [comment]
> @fermadeiral that would be great!

Great! So let's do this.

First of all, I ask you not to attach yourself to the current tests we have, because what we are going to do here is different from what we already have.

Second, I need to completely understand what @surli has in mind so I can guide you, @btellstrom.

Simon, after the last refactoring, I see we have two possibilities for testing here:
- To test `ComputeSourceDir` and `ComputeTestDir`
- To test `ComputeDir` (this could be a real unit test by calling `searchForDirs` directly from the test)

Note that one possibility does not cancel the other one, i.e. we can do both.
WDYT on this?

**Comment by surli** [comment]
I want to close those critical issues before I leave, so if it's ok I'll take this one @btellstrom @fermadeiral

**Comment by btellstrom** [comment]
It is okay with me, but if you feel like you've got the time to explain what you're doing in the tests that would be appreciated :)

**Comment by surli** [comment]
ok I'll try doing that

**Comment by fermadeiral** [comment]
@surli thanks.
