### ISSUE TITLE
Check metrics in GatherTestInformation

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/repairnator#663]
It seems there might be a mistake there in the usage of the "nb"s variables.

**Comment by surli** [comment]
Can you bring more details? I'm not sure to understand what you mean exactly here.

**Comment by fermadeiral** [comment]
For instance, this line is wrong:
`metrics.setNbRunningTests(this.nbTotalTests);`
There is a confusion between nbTotalTests and nbRunningTests: the total is the total tests found in the test suite, but sometimes not all of them are executed.

In fact, I think we should align the names in the future, because we use different words for the same thing: e.g. in `Metrics`, we have `setNbSucceedingTests` and in `Metrics4Bears`, we have `setNumberPassing`: succeeding and passing are the same thing. We should in fact to align the name of the variables in `GatherTestInformation` with the names in both metrics' classes. This may help us not to make mistakes there.

**Comment by surli** [comment]
>  I think we should align the names 

I agree. I think it's part of the refactoring to keep only one JSON files.
