### ISSUE TITLE
Move and refactor TestProjectInspector.testFailingProjectNotBuildable()?

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/repairnator#674]
WDYT on changing and moving such test to `TestBuildProject`?

**Comment by surli** [comment]
I don't agree: the idea in `TestProjectInspector` is to have tests that really calls the `ProjectInspector`. In the different steps, the idea, on the contrary, is to check only a test and to mock the project inspector if needed.

So for me, this test check the entire behavior of the inspector, so it should remain there.
