### ISSUE TITLE
release repairnator and the appropriate docker images

### ISSUE THREAD

**Issue by surli** [Spirals-Team/repairnator#691]
@btellstrom @fermadeiral I finish working on Repairnator exactly next week the 10th of august. So I propose to release a new version of Repairnator at this date with the appropriate docker images. Do you agree?

**Comment by fermadeiral** [comment]
That could be the 9th? I won't be available the 10th, and I would like to see what has been done.

**Comment by surli** [comment]
No problem then: I'll do it the 9th

**Comment by surli** [comment]
@fermadeiral do you agree if we release this new version of Repairnator as a major release. So it will be repairnator 3.0. The idea is that we changed the repairnator.json schema, so IMHO it should be released as a major version.

**Comment by fermadeiral** [comment]
It's fine by me.

**Comment by btellstrom** [comment]
Sorry about the late response, was unaware you'd leave this early into august. I'm fine with it as well.

**Comment by surli** [comment]
@btellstrom  No problem. If you have some time, you can have a look on the doc and point out if you think some things are missing. I might still have some time to improve it until tomorrow.

**Comment by surli** [comment]
So, the release is starting: now.

**Comment by fermadeiral** [comment]
Great.

**Comment by fermadeiral** [comment]
Sorry for the test failures =/

**Comment by surli** [comment]
Done.
