### ISSUE TITLE
The repairnator.json being generated does not match the repairnator-schema.json

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/repairnator#701]

**Comment by surli** [comment]
Could you provide some more info about this one? 
An example of what's wrong?

**Comment by fermadeiral** [comment]
Yes.

The following branch was generated with the current version of Repairnator, and I did not perform any mutation on this branch: https://github.com/fermadeiral/test-check-branches/tree/surli-failingProject-208897371-20170308-060702

When I run `check_branches.sh` on this branch, which was supposed to return that the branch is OK, I got a FAILURE because json file is invalid:

[ { keyword: 'required',
    dataPath: '',
    schemaPath: '#/required',
    params: { missingProperty: 'totalNumberRunningTests' },
    message: 'should have required property \'totalNumberRunningTests\'' } ]

**Comment by surli** [comment]
It's actually failing because of that change: https://github.com/Spirals-Team/repairnator/pull/618 that's weird we see it only now. I'll remove those info from the schema.

**Comment by fermadeiral** [comment]
Fixed by #706
