### ISSUE TITLE
Metrics.sizeProjectLOC: is it supposed to be in repairnator.json file?

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/repairnator#714]
I don't find any recent branch in librepair-experiments that the json file contains that property. Is that useless or should it be in the `repairnator.json`?

**Comment by surli** [comment]
It should be in repairnator.json.

**Comment by fermadeiral** [comment]
Ok. I will put it in the schema and I will fix that in the code when working with the generation of the json file.

**Comment by fermadeiral** [comment]
`ComputeSourceDir.computeMetricsOnCompleteRepo` is not working, this is why that properly has not been recorded.

**Comment by fermadeiral** [comment]
@surli I had to do `sudo apt install cloc` to make it working. I think this should be automated or we need to document it somewhere.

**Comment by surli** [comment]
Closing this one.
