### ISSUE TITLE
feat: create an argument for the from email address

### ISSUE THREAD

**Issue by surli** [Spirals-Team/repairnator#718]
The email address who sents the email notification is currently hardcoded in Repairnator. This should be settable in the configuration.

**Comment by petervasil** [comment]
Hello, can I help with this one?

**Comment by btellstrom** [comment]
Hello @petervasil, this issue is currently being worked on in PR #736, which should be ready to go very soon. I'd suggest choosing some other issue to work on :)

**Comment by btellstrom** [comment]
Resolved by #736 and #757. Closed.
