### ISSUE TITLE
Fix TestComputeSourceDir.testComputeSourceDirWithMultiModuleProject5

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/repairnator#728]
The build in PR #727, which can't be failing by its own changes, is failing due `TestComputeSourceDir.testComputeSourceDirWithMultiModuleProject5`. Such test uses a build from the project jacoco/jacoco, and apparently the problem happens when trying to do the checkout of the build's commit: I believe the issue is due the deletion of the branch where the commit was done (see https://github.com/jacoco/jacoco/pull/496), which might mean that any build triggered on repairnator will fail starting from now.

IMHO, we should remove this test from repairnator: 1) it's buggy, we can't resolve the commit; 2) there are already 4 other tests of this same type (i.e. that test the step `ComputeSourceDir` on multi-module project), and 3) the main assertion in this test is even comment.

**Comment by btellstrom** [comment]
Sounds good to me. 

I'd like to raise one question however, you seem to have detected this because of being sure that another branch should pass, can we do something to detect this in the future in the case were we actually change the behaviour of repairnator? Just try and revert things completely sometimes, or could we detect it some other way?

**Comment by btellstrom** [comment]
Could do something as simple as add a failure message to the tests with the text "if this test fails, check (github link to branch/build)" just as a reminder. Else it would be easy to get frustrated if you forget.

**Comment by fermadeiral** [comment]
This problem in specific is "easy" to detect, and I will explain you why.

First, I will start at explaining this test in specific. This test is for testing the step `ComputeSourceDir`. However, before executing such step, we need to clone and checkout a specific commit of a given build/repo, thus we execute the steps `CloneRepository`  and `CheckoutBuggyBuild` (most of our tests are like that, which is already an issue because we do not have real unit tests). Since 3 steps should be executed, we have an assertion to verify if all of them were executed (`assertThat(stepStatusList.size(), is(3));`), before doing the main assertions on the outcomes from the test.

See that in PR #727 I change nothing that could lead to a broken build: I changed a script that is not even tested. This was my first clue that something external which we depend on had changed. Repairnator logger level is set to ERROR in the tests, so sometimes is hard to identify the problem by looking at the log in the Travis build, so locally I put it in level DEBUG and run the test that is failing in Travis. I found that the problem with such test happens in that assertion that I mentioned before (`assertThat(stepStatusList.size(), is(3));`), which means that some step was not executed due failure in previous steps. In this case, I saw that the failure was in the `CheckoutBuggyBuild`, and the following message raised: `Error while testing commit: org.eclipse.jgit.errors.MissingObjectException: Missing unknown 7a70a03d005df371d0bd2091b3e2a694cbc2523e`. For me, this message can only happen if the commit does not exist OR, in our case, it did exist in the past, but not anymore (since the test was passing before and not anymore). So I went to the project that owns the commit/build being tested, and I saw that the branch where the commit belongs to had been deleted, so consequently we can't reach the commit.

So coming back to your questions:

> you seem to have detected this because of being sure that another branch should pass, can we do something to detect this in the future in the case were we actually change the behaviour of repairnator? Just try and revert things completely sometimes, or could we detect it some other way?

I was sure that my changes in that PR did not make the test to fail since I change nothing that could lead to test failures. I think we can easily detect this same type of situation only for seeing from which repo the commit is by debugging the failing test. I would like to warn you about this: this is one of the reasons why we have testing projects like surli/failingproject, fermadeiral/TestingProject, and fermadeiral/test-repairnator-bears. We know that they will be "always" there, without no deletion of stuff. This is the best way to test repairnator: with our own projects. Using our own projects, the possibilities of this type of problem happening are minimal. However, sometimes this is not easy since we want to test a specific thing that is hard for us to include in our testing projects. However again, we should always give priority to use our projects when adding tests in repairnator when we can.

> Could do something as simple as add a failure message to the tests with the text "if this test fails, check (github link to branch/build)" just as a reminder. Else it would be easy to get frustrated if you forget.

I don't think we can do like you said, i.e. "if this test fails,...", because like I explained, the majority of our tests are integration ones, and we usually need the `CheckoutBuggyBuild`, which usually have nothing to do with the main thing being tested. What we can do is to put "check (github link to branch/build)" in the message `Error while testing commit: org.eclipse.jgit.errors.MissingObjectException: Missing unknown 7a70a03d005df371d0bd2091b3e2a694cbc2523e`, which is from `GitHelper`. WDYT?

**Comment by btellstrom** [comment]
Okay, you make a very good point, and thanks for the explanation.

>I don't think we can do like you said, i.e. "if this test fails,...", because like I explained, the majority of our tests are integration ones, and we usually need the CheckoutBuggyBuild, which usually have nothing to do with the main thing being tested. What we can do is to put "check (github link to branch/build)" in the message Error while testing commit: org.eclipse.jgit.errors.MissingObjectException: Missing unknown 7a70a03d005df371d0bd2091b3e2a694cbc2523e, which is from GitHelper. WDYT?

That sounds great!
