### ISSUE TITLE
Repairnator in the media

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/repairnator#771]
Waoow, Repairnator starts to be known :1st_place_medal: 

The Register: The mysterious life of Luc Esape, bug fixer extraordinaire. His big secret? He's not human
https://www.theregister.co.uk/2018/10/17/luc_esape_bug_fixer/

**Comment by monperrus** [comment]
The Register: The mysterious life of Luc Esape, bug fixer extraordinaire. His big secret? He's not human
https://www.theregister.co.uk/2018/10/17/luc_esape_bug_fixer/

**Comment by monperrus** [comment]
Slashdot: https://slashdot.org/story/347396

**Comment by monperrus** [comment]
MIT Technology Review:
A bot disguised as a human software developer fixes bugs
https://www.technologyreview.com/s/612336/a-bot-disguised-as-a-human-software-developer-fixes-bugs/

**Comment by monperrus** [comment]
TechWorld (in Swedish): KTH-forskare har byggt en bot som patchar kod lika bra som en människa
https://techworld.idg.se/2.2524/1.709232/bot-repairnator-patchar-kod

**Comment by monperrus** [comment]
CnBeta: 机器人程序像人类程序员一样修 bug
https://www.cnbeta.com/articles/tech/781167.htm

**Comment by monperrus** [comment]
Boing Boing: A bot has been finding bugs and submitting patches for them, successfully masquerading as a human
https://boingboing.net/2018/10/19/repairnator-is-everywhere.html

**Comment by monperrus** [comment]
Global CIO: Бот Repairnator ищет ошибки в коде и пишет заплатки
http://www.globalcio.ru/news/7347/

**Comment by monperrus** [comment]
Habr: Замаскированный под программиста бот исправляет ошибки в коде
https://habr.com/post/427775/

**Comment by monperrus** [comment]
厉害了！一名机器人成功伪装成人类贡献修复补丁- 开源中国
https://www.oschina.net/news/101186/a-bot-fixes-bugs

机器人伪装成人类在GitHub 上为开源项目修复bug - 知乎 - 知乎专栏
https://zhuanlan.zhihu.com/p/47737355

程序员的革命or灾难：机器人在GitHub修复bug、与人不相上下（附论文 ...
https://developer.51cto.com/art/201810/585782.htm
漫话：程序员要失业了？？！机器人开始在GitHub上修Bug了。 - IT程序猿
https://www.itcodemonkey.com/article/10883.html

工程師小幫手？瑞典團隊開發出有人類修 Bug 水準的機器人
https://technews.tw/2018/10/27/repairnator/

机器人在GitHub 修复bug、与人不相上下- 腾讯网
https://xw.qq.com/cmsid/20181026A1449500

机器人都能成功编写和修复补丁了，程序猿这是真的要失业？
https://www.chainnews.com/articles/284546559370.htm

程序员的革命or灾难：机器人在GitHub修复bug、与人不相上下（附论文 ...
www.souhunjia.com/art/201810/585782.htm

**Comment by monperrus** [comment]
นักวิจัยสร้าง Bot สำหรับค้นหาบั๊กและพัฒนา Patch คุณภาพสูงเองได้สำเร็จ
https://www.techtalkthai.com/repairnator-bot-could-automatically-fix-bugs-for-you/

Bot giờ đây đã có khả năng fix bug thay cho lập trình viên
https://techtalk.vn/da-xuat-hien-bot-co-kha-nang-fix-bug-thay-cho-lap-trinh-vien.html

**Comment by monperrus** [comment]
På Svenska:
AI och samhällsutvecklingen
https://sverigesradio.se/sida/artikel.aspx?programid=1637&artikel=7138149

**Comment by monperrus** [comment]
En français:
Repairnator, un bot capable de rivaliser avec les développeurs pour trouver et corriger des bogues, un pas vers l'automatisation du codage ?
https://www.developpez.com/actu/230678/Repairnator-un-bot-capable-de-rivaliser-avec-les-developpeurs-pour-trouver-et-corriger-des-bogues-un-pas-vers-l-automatisation-du-codage/

**Comment by monperrus** [comment]
![Screenshot from 2020-09-08 12-43-23](https://user-images.githubusercontent.com/803666/92466891-4ca33280-f1c0-11ea-89b1-bb7d43d93d03.png)

https://www.youtube.com/watch?v=sHkogNGyBSs

**Comment by martinezmatias** [comment]
En Español: 
El “Repairnator” será el Terminator que acabará no sólo con la raza de testers sino además con los desarrolladores?
https://testingbaires.com/el-reparnaitor-sera-el-terminator-que-acabara-no-solo-con-la-raza-de-testers-sino-ademas-con-los-desarrolladores/

Repairnator, el bot que detecta y arregla fallos de software igual que un humano
https://www.technologyreview.es/s/10642/repairnator-el-bot-que-detecta-y-arregla-fallos-de-software-igual-que-un-humano
