### ISSUE TITLE
Refactoring on dates.

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/repairnator#773]
@surli and @bloriot97, from the issue #772, I realized that we always do `new Date()` to refer to the end of the reproduction, but this is prone to inconsistencies (very difficult to happen, but it could happen) in the db, thus we might refactor that to always record the same exact date, which would be in `ReproductionBuggyBuild.getReproductionDateEnd` I think (to be precisely checked), WDYT?

**Comment by surli** [comment]
I think we should provide in repairnator-core a class `DateUtils` and use it everywhere we need to work with dates :)
Pretty easy to find all places where we import `java.util.Date` and to put the right method in a `DateUtils`.

**Comment by fermadeiral** [comment]
Refactoring on dates (this issue is not supposed to fix any bug, it's just related to refactorings and minor adjustments):

- Create `DateUtils` for everything related to dates
- Replace `new Date()` to `ReproductionBuggyBuild.getReproductionDateEnd` to serialize `buildReproductionDate`
- ?
