### ISSUE TITLE
A link in the root README.md is broken.

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/repairnator#777]
The contribution guidelines link is broken in this part of the root README.md:

```
### Integration

If you want to bring your own tool in Repairnator, have a look on [contribution guidelines](/doc/contribute.md) :smile:
```

I don't fix it because I don't know which link is the correct one.

Note also that there are things being said about contributing in that other README: https://github.com/Spirals-Team/repairnator/blob/master/doc/README.md

**Comment by bloriot97** [comment]
fixed  by  #781.
