### ISSUE TITLE
operate repairnator on KTH box 

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/repairnator#779]
* [x] get a KTH box
* [x] deploy a database (on SNIC)
* [x] send emails :hammer: for patches (#734 is one next step)
* [x] deploy the dashboard on KTH box

**Comment by monperrus** [comment]
@btellstrom has a box.

**Comment by monperrus** [comment]
Repairnator sends email through the KTH SMTP server with user "testbt". The password in a config file on the box.

**Comment by btellstrom** [comment]
It is now running on SNIC, with http://130.239.81.199/

**Comment by monperrus** [comment]
excellent!
