### ISSUE TITLE
question: about database JSON schemas

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/repairnator#795]
Hi Simon,

There are a number of schemas in https://github.com/Spirals-Team/repairnator/tree/master/doc/chore/mongo

At which point do we check that the data complies with them?

--Martin

**Comment by surli** [comment]
> At which point do we check that the data complies with them?

we don't. At least not automatically. I added them only for documentation purpose, for the data stored in the DB.

**Comment by monperrus** [comment]
OK thanks.

They are already becoming outdated.

What's reasonable to your opinion, should we enforce them or should we delete from the repo before
they become too confusing?

**Comment by surli** [comment]
> What's reasonable to your opinion, should we enforce them or should we delete from the repo before they become too confusing?

I think they're a good doc for anyone who gets a snapshot of our data and wants to process them. So if in the future you want to expose a dataset coming from  Repairnator, you'll necessarily need this kind of schema to explain the organization of the data.
So IMO we should at least keep them up-to-date.

**Comment by monperrus** [comment]
Agree. What's the command to regenerate them?

**Comment by surli** [comment]
None. It's semi automatic. I used https://www.jsonschema.net and a sample of our data.

**Comment by monperrus** [comment]
OK thanks.
