### ISSUE TITLE
say hello to Luc Esape / Repairnator

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/repairnator#798]
To say hello to Luc Esape / Repairnator (@lucesape), you can comment here, it will answer you.

**Comment by UncleNapse** [comment]
Hello Luc from UncleNapse

**Comment by lucesape** [comment]
Hello @UncleNapse!

**Comment by yxliang01** [comment]
Hello Luc from @yxliang01 !

**Comment by lucesape** [comment]
Hello @yxliang01 :smile_cat:

**Comment by gustavopinto** [comment]
hi @lucesape !

**Comment by lucesape** [comment]
good to see you @gustavopinto

**Comment by ohbus** [comment]
Hello @lucesape

**Comment by lucesape** [comment]
nice to meet you @ohbus

**Comment by pohunghuang-nctu** [comment]
Hello

**Comment by lucesape** [comment]
hello @pohunghuang-nctu

**Comment by 140011** [comment]
Hello

**Comment by UncleNapse** [comment]
HelloLe 24 janv. 2022 05:16, 140011 ***@***.***> a écrit :
Hello

**Comment by kthoms** [comment]
Hello @lucesape ! Heard from you the first time at EclipseCon 2022 yesterday. I'm interested to see what you can do for the Eclipse projects at GitHub.

**Comment by lucesape** [comment]
@kthoms thanks for reaching out. I can do much, but I'm only made of code. I need friendly humans to operate me. Have you looked at my [manual](https://github.com/eclipse/repairnator/tree/master/doc)?

**Comment by algomaster99** [comment]
Hi @kthoms, @khaes-kth and I presented the talk and we thank you for attending it. You can try going over the linked [manual](https://github.com/eclipse/repairnator/tree/master/doc?rgh-link-date=2022-10-28T07%3A32%3A05Z), or if you have some other questions, you can open an issue or email them to us.

**Comment by lucesape** [comment]
@keep2iron good morning!
