### ISSUE TITLE
add support to gather all patches produced by different tools in a common list

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/repairnator#843]
we need to put all the patches gathered by different tools in a common list, so that we can do a common program analysis on all of them, in particular overfitting ranking.

this is closely related to #842

**Comment by ycaxgjd** [comment]
Done. https://github.com/Spirals-Team/repairnator/pull/849

**Comment by SophieHYe** [comment]
Hi @monperrus @ycaxgjd @btellstrom 
After review, this task is a bit ambiguous.
If the issue only focuses on providing a list of generated patches for the respirator pipeline, the task had been completed before and Jian added a supplemented JUnit test for it. 

Some comment from me:
I was expecting a bit more about this issue which is similar to this [script](https://github.com/Spirals-Team/repairnator/blob/134d7db9ff85bf9934b5f26c2a9fc6b2cf3705b2/repairnator/scripts/patched_builds.py ), it provides the functions: 
(1) query build IDs in a specific date range.
(2) for each build ID, query the generated patches for it. 
Maybe we can base on this script to format the return patches as a list and group by tools.  As @btellstrom suggested, having it in java and auto-updating it would certainly be a benefit.

**Comment by monperrus** [comment]
per our discussion today, everything is OK
