### ISSUE TITLE
Docker image outdated

### ISSUE THREAD

**Issue by btellstrom** [Spirals-Team/repairnator#848]
Currently we are unable to build a new pipeline image, most likely due to the base image (`maven:3.3.9-jdk-8`) being outdated. 

This is hindering troubleshooting and deployment of new versions of the pipeline.

**Comment by btellstrom** [comment]
Resolved by #851

**Comment by monperrus** [comment]
FYI: Docker continuous delivery up and running again.

image "repairnator/pipeline" pushed

see https://travis-ci.org/Spirals-Team/repairnator/jobs/561075363
